name: update-modlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC, adjust as needed

jobs:
  update-modlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./  # root of repo after checkout

      - name: Run modlist setup script
        run: node setup_launcher.js
        working-directory: ./  # root of repo

      - name: Commit and push updated modlist JSON
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./app/distros/NewHorizons.json
          git diff --cached --quiet || git commit -m "Update modlist JSON [skip ci]"
          git push
        working-directory: ./  # root of repo
