name: Update Modlist and Build Launcher

on:
  schedule:
    - cron: '0 3 * * *'  # daily 03:00 UTC
  workflow_dispatch:    # manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run modlist generation script
        run: node setup_launcher.js

      - name: Build Windows executable with pkg
        run: |
          npm install -g pkg
          pkg . --targets node18-win-x64 --output NewHorizonsLauncher.exe

      - name: Upload Windows executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: NewHorizonsLauncher-win
          path: NewHorizonsLauncher.exe
