name: Update Modlist and Build Launcher

on:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC
  workflow_dispatch:      # manual trigger

jobs:
  update-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate modlist JSON
        run: node setup_launcher.js

      - name: Build Windows executable
        run: npm run build-win

      - name: Commit and push updated modlist JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./app/distros/NewHorizons.json ./build/NewHorizons.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated modlist update and build"
            git push origin main
          fi

      - name: Upload Windows executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: NewHorizonsLauncher-Windows
          path: ./build/NewHorizonsLauncher.exe
