name: Update Modlist and Build Launcher

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC; adjust as needed
  workflow_dispatch:    # Allows manual triggering from GitHub UI

jobs:
  update-modlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # or your preferred stable Node version

      - name: Install dependencies
        run: npm install

      - name: Run modlist setup script
        run: node setup_launcher.js

      - name: Commit and push updated modlist JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./app/distros/NewHorizons.json package-lock.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Automated modlist update"
          git push

      - name: Install pkg to build executable
        run: npm install -g pkg

      - name: Build Windows executable
        run: pkg ./setup_launcher.js --output ./app/distros/NewHorizonsLauncher.exe --targets node18-win-x64

      - name: Upload Windows launcher exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: NewHorizonsLauncher
          path: ./app/distros/NewHorizonsLauncher.exe
